#!/usr/bin/env node
// scenario.json → Playwright *.spec.ts. run.mjs와 같은 단계 어휘·같은 판정(10초 대기, url은 "/"면 pathname 일치)
// usage: node emit-test.mjs scenario.json > tests/e2e/<name>.spec.ts
import { readFile } from "node:fs/promises";
import { basename } from "node:path";

const q = JSON.stringify;
const reEsc = (s) => s.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");

function lines(step) {
  if (step.goto != null) return [`await page.goto(${q(step.goto)});`];
  if (step.click != null) return [`await page.click(${q(step.click)});`];
  if (step.fill != null) return [`await page.fill(${q(step.fill[0])}, ${q(step.fill[1])});`];
  if (step.select != null) return [`await page.selectOption(${q(step.select[0])}, ${q(step.select[1])});`];
  if (step.expect != null) {
    const { url, text, visible } = step.expect;
    const out = [];
    if (url != null) {
      const src = url.startsWith("/") ? `^[a-z]+://[^/]+${reEsc(url)}([?#]|$)` : reEsc(url);
      out.push(`await expect(page).toHaveURL(new RegExp(${q(src)}));`);
    }
    if (text != null) out.push(`await expect(page.getByText(${q(text)}).first()).toBeVisible();`);
    if (visible != null) out.push(`await expect(page.locator(${q(visible)}).first()).toBeVisible();`);
    return out;
  }
  throw new Error(`unknown step: ${q(step)}`);
}

export function emit(s) {
  return `// generated by taperun from scenario ${q(s.name)}
import { test, expect as baseExpect } from "@playwright/test";

const expect = baseExpect.configure({ timeout: 10_000 });
test.use({ baseURL: ${q(s.baseURL)}, actionTimeout: 10_000 });

test(${q(s.name)}, async ({ page }) => {
${s.steps.flatMap(lines).map((l) => `  ${l}`).join("\n")}
});
`;
}

if (process.argv[1] && new URL(import.meta.url).pathname.endsWith(basename(process.argv[1]))) {
  const file = process.argv[2];
  if (!file) { console.error("usage: emit-test.mjs scenario.json"); process.exit(2); }
  process.stdout.write(emit(JSON.parse(await readFile(file, "utf8"))));
}
